/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { PerspectiveCamera, useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/08SrAZtLm6j67LuU/scene.splinecode"
  );

  const { scene } = useGLTF("/assets/david_is_my_dad.gltf");
  return (
    <motion.primitive
      object={scene}
      position={[-0.24, -0.75, 0.71]}
      rotation={[0, -0.04, -0.06]}
      scale={[0.52, 0.52, 0.52]}
    />
  );
}
